version: 2

seeds:
  - name: astropixels_soleq
    description: >
      Solstice and Equinox datetimes for years 2001-2100 sourced from https://www.astropixels.com/ephemeris/soleq2001.html:
      Earth's rotational axis tilted about 23.5° from the perpendicular with respect to Earth's orbit around the Sun. As a result, the amount that Earth’s axis tilts towards or away from the Sun varies during the year.
      Summer Solstice occurs at the moment the tilt of Earth's axis towards the Sun is at a maximum. The Sun then appears at its highest elevation at noon for observers in the Northern Hemisphere. Summer Solstice marks the longest day and shortest night of the year in the Northern Hemisphere.
      Winter Solstice occurs at the moment the tilt of Earth's axis away the Sun is at a maximum. The Sun then appears at its lowest elevation at noon for observers in the Northern Hemisphere. Winter Solstice marks the shortest day and longest night of the year in the Northern Hemisphere.
      There are two times a year when Earth's axis neither tilts towards or away from the Sun. In fact, the axis then perpendicular to the Sun resulting in a nearly equal length of day and night at all latitudes. These instances are referred to as equinoxes (derived from two Latin words: aequus (equal) and nox (night)). The two equinoxes are nearly six month apart and are known as the Spring Equinox and Fall Equinox.
      
      Acknowledgement
      All calculations are by Fred Espenak, and he assumes full responsibility for their accuracy. Algorithms used in predicting Earth's solstices and equinoxes are based on Astronomical Algorithms by Jean Meeus (Willmann-Bell, Inc., Richmond, 1998).
      Permission is freely granted to reproduce this data when accompanied by the acknowledgment:
      "Solstice and Equinox Table Courtesy of Fred Espenak, www.Astropixels.com".
    columns:
      - name: year
      - name: spring_equinox
      - name: summer_solstice
      - name: fall_equinox
      - name: winter_solstice
    config:
      post_hook: alter table {{ this }} set change_tracking=true